@startwbs
* client

** gui

*** autenticazione
*** azioniLoggato
*** azioniRistoratore
*** listeRistoratore
*** listeUtente
*** menu
*** utils
*** TemplateGUI

** main
*** ClientMain

** network
*** ClientConnection

@endwbs