@startwbs
* server

** dao
*** PreferitiDAO
*** RecensioneDAO
*** RistoranteDAO
*** TipoCucinaDAO
*** UtenteDAO

** db
*** DatabaseConnection

** exception
*** PreferitiException
*** RecensioniException
*** RistoranteException
*** UtenteException

** main
*** ServerMain

** network
*** ClientHandler

** security
*** PasswordPolicy
*** PasswordService
*** PasswordUtils

** service
*** PreferitiService
*** RecensioneService
*** RistoranteService
*** RistoratoreService
*** TipoCucinaService
*** UtenteService
*** ValidationUtils

@endwbs