@startwbs
* shared

** communication
*** Richiesta
*** Risposta
*** TipoRichieste

** domain
*** Preferito
*** Recensione
*** Ristorante
*** Utente

** dto
*** FiltroRicercaDTO
*** LoginDTO
*** PreferitiDTO
*** RecensioneDTO
*** RegistrazioneDTO
*** RiepilogoRecensioniDTO
*** RistoranteDTO
*** TipoCucinaDTO

** enums
*** CampoRecensioni
*** CampoRistorante
*** CampoUtente
*** RuoloUtente

@endwbs